# Generated by Django 4.1 on 2022-08-25 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lattitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('amenities', models.ManyToManyField(blank=True, to='HavenRouteApp.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_list', models.ManyToManyField(through='HavenRouteApp.Cruise', to='HavenRouteApp.port')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HavenRouteApp.port')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HavenRouteApp.route')),
            ],
        ),
        migrations.AddField(
            model_name='cruise',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HavenRouteApp.port'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HavenRouteApp.route'),
        ),
    ]