# Generated by Django 4.1 on 2022-08-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HavenRouteApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='p',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='r',
        ),
        migrations.AlterField(
            model_name='route',
            name='stop_list',
            field=models.ManyToManyField(through='HavenRouteApp.RoutePort', to='HavenRouteApp.port'),
        ),
    ]