# Generated by Django 4.1 on 2022-08-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HavenRouteApp', '0002_remove_cruise_p_remove_cruise_r_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='description',
            field=models.TextField(default=''),
        ),
    ]