# Generated by Django 4.1 on 2022-08-26 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HavenRouteApp', '0004_cruise_route_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='attendees',
            field=models.ManyToManyField(related_name='trip_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cruise',
            name='created_by',
            field=models.ManyToManyField(related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
