# Generated by Django 4.1 on 2022-08-26 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HavenRouteApp', '0005_cruise_attendees_cruise_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='created_by',
        ),
        migrations.AddField(
            model_name='cruise',
            name='crew',
            field=models.ManyToManyField(related_name='crew', to=settings.AUTH_USER_MODEL),
        ),
    ]
